# 生成3D高斯泼溅，8 通道的潜变量解码成高斯椭球
_target_: sam3d_objects.model.backbone.tdfy_dit.models.structured_latent_vae.decoder_gs.SLatGaussianDecoderTdfyWrapper
resolution: 64 # 分辨率
model_channels: 768 # 隐藏层通道
latent_channels: 8  # 输入通道
num_blocks: 12      # 12个 swin_transformer
num_heads: 12       # 12个头
mlp_ratio: 4
attn_mode: swin
window_size: 8      # 窗口大小8
# 关键参数
representation_config:
# 5个属性描述一个椭球
  lr:
    _xyz: 1.0   # 位置
    _features_dc: 1.0 # 颜色
    _opacity: 1.0 # 不透明度
    _scaling: 1.0 # 球大小（长宽高）
    _rotation: 0.1  # 球方向（四元数）
  perturb_offset: true
  voxel_size: 1.5
  num_gaussians: 32   # 每个体素预测出32个高斯球
  2d_filter_kernel_size: 0.1
  3d_filter_kernel_size: 0.0009
  scaling_bias: 0.004
  opacity_bias: 0.1
  scaling_activation: softplus
use_fp16: true
