# 结构化潜变量网格解码器
_target_: sam3d_objects.model.backbone.tdfy_dit.models.structured_latent_vae.decoder_mesh.SLatMeshDecoderTdfyWrapper
resolution: 64
model_channels: 768 # 特征维度 768
latent_channels: 8 # 输入
num_blocks: 12  # 12个 Swin Transformer
num_heads: 12
mlp_ratio: 4
attn_mode: swin
window_size: 8
representation_config:
  use_color: true # 生成颜色
use_fp16: true
