_target_: sam3d_objects.model.backbone.tdfy_dit.models.sparse_structure_vae.SparseStructureDecoderTdfyWrapper
out_channels: 1    
latent_channels: 8 
num_res_blocks: 2
num_res_blocks_middle: 2

channels:
- 512
- 128
- 32
reshape_input_to_cube: false
